### ISSUE TITLE
Send lock command to both PC's

### ISSUE THREAD

**Issue by AlaricEgli** [hrvach/deskhop#104]
The situations where I'd need to lock one PC but not the other are extremely rare. Is it possible to make the 'Windows key"+L command go out to both PCs regardless of which machine is active at that moment?

**Comment by hrvach** [comment]
There is such a feature already, but you need to tell the box what operating systems you have, so it knows what shortcut to send. Check the list of shortcuts ... The updated version will have GUI settings so it will be easier to define OS.
