### ISSUE TITLE
Caps lock  sometimes stuck after entering web config mode (pressing left shift + right shift + c + o) 

### ISSUE THREAD

**Issue by chris-010** [hrvach/deskhop#109]
Strage behavior after after pressing the key combination (pressing left shift + right shift + c + o) to enter the web config mode. Sometimes the caps lock seems to be stucked and the mouse select position is locked, because text is highlighted outgoing from that position. The capslock led does not light up in that case.

System is Windows.

**Workaround:**
- shift
- ctrl+alt+del
- esc

**Comment by hrvach** [comment]
Thanks, this is very useful - I think I know what might be happening here, I'll try fixing in 0.61

**Comment by chris-010** [comment]
Tested it several times with 0.61, problem is solved now, thanks a lot.
