### ISSUE TITLE
WebIf read wrong device values

### ISSUE THREAD

**Issue by chris-010** [hrvach/deskhop#110]
On first attempt when hitting the read button to get device settings, i just get random values.
It's just working on second attempt.

**Comment by hrvach** [comment]
All of them or just some?

**Comment by chris-010** [comment]
I'm not sure if all, but at least some values as i could notice.

**Comment by chris-010** [comment]
First read **attempt**
![image](https://github.com/hrvach/deskhop/assets/10660568/746f1ad2-87d6-47bb-889a-f1e38b855ff4)


Second read **attempt**
![image](https://github.com/hrvach/deskhop/assets/10660568/213f9ec2-277b-4c48-8411-ee5620f10b2f)

**Comment by tomjohnstone** [comment]
I had the same issue when upgrading to the RC. Everytime I would change config settings and reload the config page they would be corrupted. I fixed the issue by wiping my config first.

**Comment by hrvach** [comment]
Thanks for noticing this, I have an idea why this might have been happening and reworked that part of the readout code so it should be more stable. 0.62 will be available as soon as I find some free time to update/rebuild/package.

**Comment by hrvach** [comment]
This should be resolved, I think. Please let me know if it happens again.
