### ISSUE TITLE
Problem compiling...

### ISSUE THREAD

**Issue by Bunny-Head** [hrvach/deskhop#114]
After installing CMake & gcc-arm-none-eabi, and after doing cmake -S . -B build on main directory, I get this:

-- Building for: NMake Makefiles
PICO_SDK_PATH is C:/Users/Fali/Downloads/deskhop-main/pico-sdk
Defaulting PICO_PLATFORM to rp2040 since not specified.
Defaulting PICO platform compiler to pico_arm_gcc since not specified.
-- Defaulting build type to 'Release' since not specified.
PICO compiler is pico_arm_gcc
CMake Error at CMakeLists.txt:12 (project):
  Running

   'nmake' '-?'

  failed with:

   no such file or directory

-- Configuring incomplete, errors occurred!

Can somebody help me with the next step please?

EDIT: If I delete CMakeCache.txt and do "cmake -S . -B build -G "MinGW Makefiles" i get:

PICO_SDK_PATH is C:/Users/Fali/Downloads/deskhop-main/pico-sdk
Defaulting PICO_PLATFORM to rp2040 since not specified.
Defaulting PICO platform compiler to pico_arm_gcc since not specified.
-- Defaulting build type to 'Release' since not specified.
PICO compiler is pico_arm_gcc
CMake Error: CMake was unable to find a build program corresponding to "MinGW Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!

EDIT 2: Managed to do the first part by installing MinGW-w64. Now I have this issue:

[  1%] Building ASM object pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default.dir/compile_time_choice.S.obj
[  1%] Linking ASM executable bs2_default.elf
[  1%] Built target bs2_default
[  2%] Generating bs2_default.bin
[  2%] Generating bs2_default_padded_checksummed.S
[  2%] Built target bs2_default_padded_checksummed_asm
[  3%] Creating directories for 'PioasmBuild'
[  4%] No download step for 'PioasmBuild'
[  5%] No update step for 'PioasmBuild'
[  5%] No patch step for 'PioasmBuild'
[  5%] Performing configure step for 'PioasmBuild'
loading initial cache file C:/Users/Fali/Downloads/deskhop-main/build/pioasm/tmp/PioasmBuild-cache-Release.cmake
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
CMakeFiles\PioasmBuild.dir\build.make:90: recipe for target 'pioasm/src/PioasmBuild-stamp/PioasmBuild-configure' failed
mingw32-make.exe[2]: *** [pioasm/src/PioasmBuild-stamp/PioasmBuild-configure] Error 1
CMakeFiles\Makefile2:1506: recipe for target 'CMakeFiles/PioasmBuild.dir/all' failed
mingw32-make.exe[1]: *** [CMakeFiles/PioasmBuild.dir/all] Error 2
Makefile:89: recipe for target 'all' failed
mingw32-make.exe: *** [all] Error 2

**Comment by chris-010** [comment]
I did not get it working on windows either, so i moved to linux for compiling.

**Comment by hrvach** [comment]
I never tried building it on Windows, so I can't help much there. If anyone has, please share instructions and I'll add them to the wiki. For the time being, I'd advise sticking to Linux.

**Comment by tomjohnstone** [comment]
> I never tried building it on Windows, so I can't help much there. If anyone has, please share instructions and I'll add them to the wiki. For the time being, I'd advise sticking to Linux.

Instructions for Windows compilation:

1. Run through setup for WSL (Ubuntu): https://learn.microsoft.com/en-us/windows/wsl/install
2. Open a Linux shell by running `ubuntu` from a Windows command prompt or the run menu
3. Enter the following commands to setup pre-requisites:
```
sudo apt-get update
sudo apt install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib g++
git clone https://github.com/hrvach/deskhop.git
cmake -S . -B build
```
4. Compile code:
```
cmake --build build
```

**Comment by jalmeroth** [comment]
Can we close this issue?

**Comment by Bunny-Head** [comment]
Solved!
