### ISSUE TITLE
v1 PCB from elecrow

### ISSUE THREAD

**Issue by jnichols35** [hrvach/deskhop#120]
I ordered the PCB from elecrow and didn't see an option to select which version of the PCB and assumed it was the v1.1 based on the pictures. I ordered the BOM for v1.1, so now I'm not sure what to do. 

Has this happened to anyone else?

**Comment by hrvach** [comment]
Don't worry - I believe they don't even do v1.0. You should be fine! If you get stuck during assembly, let me know and I'll try helping out.

**Comment by jnichols35** [comment]
Sorry, I already received the PCB, and it's for v1. 
![PXL_20240708_153825536](https://github.com/hrvach/deskhop/assets/26259981/1a8bf789-a4a9-40a0-adc2-53f9a0e5583a)
![PXL_20240708_153830548](https://github.com/hrvach/deskhop/assets/26259981/707b7235-ba2e-4e55-a550-029d53ba2299)

**Comment by hrvach** [comment]
Oh man, I had no idea ... I'll try asking them why the pcb 1.0 is even sold - this should not be the case. 0805 caps will be a bit smaller but I've fit them into 1206 many times when I didn't have 1206 (and vice versa, but that's embarassing to admit)

**Comment by OrpheeGT** [comment]
Does it means even if you order the whole package, it comes disassembled ? I expected it to be all soldered / ready to use... ?

**Comment by hrvach** [comment]
I believe it comes assembled if you order the whole package, or just the assembled board. The only way you'd need to solder if you order just the bare PCB (that's my understanding). I asked Elecrow and they agreed to switch to v1.1, my assumption is after they clear out existing stock.

**Comment by jnichols35** [comment]
@hrvach Thanks for looking into this, I also emailed Elecrow about it. I think having the option to choose which version of the board would be enough. Was confusing since their pictures were pretty much all for the updated PCB. 

Regardless, I'm good here, going to see about getting the BOM for v1 and just make both versions for fun.

**Comment by hrvach** [comment]
> @hrvach Thanks for looking into this, I also emailed Elecrow about it. I think having the option to choose which version of the board would be enough. Was confusing since their pictures were pretty much all for the updated PCB.
> 
> Regardless, I'm good here, going to see about getting the BOM for v1 and just make both versions for fun.

I'm really sorry about the confusion, some things get lost in translation and it's very hard to know what's actually shipped when you have no insight into it... 

Best of luck with assembling it and hope it works on the first try! :)
