### ISSUE TITLE
Caps lock / num lock LEDs only work on output A

### ISSUE THREAD

**Issue by Fallingonion** [hrvach/deskhop#137]
Hi all... a small cosmetic issue on v0.63, possibly on earlier versions also?
On my keyboard (a Logitech G815) the caps lock and num lock LEDs only work on output A, but not on output B. 
Is this as expected, or am I doing something stupid? I can't remember if it worked on both on previous versions...

Thanks :)

**Comment by hrvach** [comment]
Good catch, I think I know what might be going on. Will try to fix in the next release.

**Comment by hrvach** [comment]
Please check the pre-release (v0.64), better now?

**Comment by Fallingonion** [comment]
Caps lock works correctly now, thanks!  I can't test num lock since the second machine is a laptop with no numpad, so doesn't have a numlock key, but I assume it works :) 
Thanks!

**Comment by hrvach** [comment]
Really appreciate you catching this one, not trivial to notice and I would have never fixed it otherwise. Thanks for helping the project with bug reports!

**Comment by Fallingonion** [comment]
Thank *you* for fixing things so quickly!
