### ISSUE TITLE
Custom shortcuts

### ISSUE THREAD

**Issue by Bunny-Head** [hrvach/deskhop#147]
Hello!

I keep pressing some shortcuts by accident so I was wondering if you plan to add a way to customize shortcuts. I know I could do it by compiling the source but for now, I have no much idea on how to do it (actually  learning).

As always, thank you!

**Comment by hrvach** [comment]
I am notoriously bad at choosing shortcuts. Configurable shortcuts are planned, but first more bugfixing and addressing some of the more pressing issues... sadly never enough time.

**Comment by Bunny-Head** [comment]
Thanks! Can't donate time so next month will send you for a pair of beers on my name! Take all the time in the world, please.
