### ISSUE TITLE
Slow mouse movement

### ISSUE THREAD

**Issue by liuhao1946** [hrvach/deskhop#15]
Thank you for your open-source project. On the day you released it, I made a board according to the PCB you provided.

After downloading the latest firmware today, I found that the mouse moves very slowly on two screens. Can you tell me where I can adjust the mouse speed? Maybe this parameter can be exposed.

**My computer configuration:**
Mouse: Logitech wireless mouse.
Keyboard: 2.4G wireless keyboard.
Computer A: Desktop computer, Windows 10, screen resolution is 1920 x 1080.
Computer B: Laptop computer, Windows 10, screen resolution is 2560 x 1600.

Thank you again.

**Comment by hrvach** [comment]
Check user_config header file, it should be configurable there! I never got to test on any Logitech gear so I'm actually super happy that it works haha :)

**Comment by hrvach** [comment]
Thanks for being a beta tester and for your patience! It would be awesome if you could send your raw HID descriptor so I can try to figure out what's different from my setup and fix it for everyone who might experience the same issue. Cheers!

**Comment by hrvach** [comment]
To avoid duplication, continuing to track in #17
