### ISSUE TITLE
Game mode not working on 0.64?

### ISSUE THREAD

**Issue by Fallingonion** [hrvach/deskhop#152]
It appears that game mode doesn't work on 0.64, for me at least...using the new left ctrl + right shift + G shortcut, the LEDs flicker, but the mouse is not locked to the target screen.
Anyone else experiencing this?

**Comment by hrvach** [comment]
Thanks for the report - will check today, there is a chance I broke it by fixing another bug.

**Comment by hrvach** [comment]
v0.65 should fix this. Please let me know if it's still an issue or it works as expected now. Patching the issue with "jumpy cursor" for the windows workaround accidentally broke gaming mode and I'm no gamer so haven't noticed :) Apologies!

**Comment by Fallingonion** [comment]
All working now, thanks as always!
