### ISSUE TITLE
USB Drive "DESKHOP" does not appear /Volumes on macOS

### ISSUE THREAD

**Issue by adofse** [hrvach/deskhop#159]
I just got Deskhop and trying to configure via Web configuration mode.

However, /Volumes/DESKHOP does not appear by pressing Left Ctrl + Right Shift + C + O.

Both micro USB are connected to two machines and keyboard side of LED is started blinking when I press  Left Ctrl + Right Shift + C + O.

Any way to mount Deskhop and use web configuration mode on macOS?

Firmware: pre-built v0.65.
Machine: MacOS Sonoma 14.6.1

**Comment by hrvach** [comment]
Is the side blinking connected to MacOS?

**Comment by adofse** [comment]
Yes.

**Comment by hrvach** [comment]
I've tried it on Sonoma 14.6.1 and haven't seen any issues. Do you have any security software installed that would prevent usb drives from being mounted or a similar known restriction?

**Comment by adofse** [comment]
Using different USB micro cable solved this issue!
