### ISSUE TITLE
Remain functional when only single computer connected

### ISSUE THREAD

**Issue by nautmichio** [hrvach/deskhop#169]
Hello, 
Thanks for this project. I am not sure if this is possible but I often disconnect my laptop and use it away from my desk. Since the mouse is plugged into the side that would be plugged into my laptop it no longer works. Is there someway to let the deskhop still remain functional with only one side of it plugged in?

Thanks.

**Comment by hrvach** [comment]
You can plug in another cable from your desktop or anything else with a microusb that carries power. I'm trying to finish a PCB that solves that problem with ADuM3160, having just one port isolated (so both inputs are covered from one side).
