### ISSUE TITLE
I would like to support this project

### ISSUE THREAD

**Issue by chris17453** [hrvach/deskhop#18]
Dear Hrvoje,

Firstly, I must commend you on the exceptional work you've done with your project. It's  impressive as heck!

I've built two deskhoppers, and they're performing wonderfully. As someone who greatly appreciates the effort you have put in, I feel inclined to offer my support.

Would your project benefit from additional hardware for testing, like a specific type of Logitech mouse or a unique keyboard? I'm also open to providing financial support or purchasing necessary test equipment for you. I believe in supporting valuable open-source projects, and yours has certainly been beneficial in practical terms.

Looking forward to potentially collaborating with you.

Best wishes,
-Chris
chris@watkinslabs.com

**Comment by hrvach** [comment]
Hey Chris!

Please allow me to thank you for the kind words first, that really means a lot! You are more than welcome to help in any way you wish other than financial support. Trying out new versions and reporting back would be awesome, as it's quite challenging to support a gazillion different devices. Any other kind of collaboration is also more than welcome, and thank you so much for offering!

Best,

Hrvoje
