### ISSUE TITLE
Support for Apple Mighty Mouse

### ISSUE THREAD

**Issue by jalmeroth** [hrvach/deskhop#185]
Hi,

I discovered a very exotic HID descriptor in Apples Mighty Mouse:

```
0x05, 0x01,        // Usage Page (Generic Desktop Ctrls)
0x09, 0x02,        // Usage (Mouse)
0xA1, 0x01,        // Collection (Application)
0x05, 0x09,        //   Usage Page (Button)
0x19, 0x01,        //   Usage Minimum (0x01)
0x29, 0x04,        //   Usage Maximum (0x04)
0x15, 0x00,        //   Logical Minimum (0)
0x25, 0x01,        //   Logical Maximum (1)
0x95, 0x04,        //   Report Count (4)
0x75, 0x01,        //   Report Size (1)
0x81, 0x02,        //   Input (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position)
0x95, 0x01,        //   Report Count (1)
0x75, 0x04,        //   Report Size (4)
0x81, 0x01,        //   Input (Const,Array,Abs,No Wrap,Linear,Preferred State,No Null Position)
0x05, 0x01,        //   Usage Page (Generic Desktop Ctrls)
0x09, 0x01,        //   Usage (Pointer)
0xA1, 0x00,        //   Collection (Physical)
0x09, 0x30,        //     Usage (X)
0x09, 0x31,        //     Usage (Y)
0x09, 0x32,        //     Usage (Z)
0x09, 0x38,        //     Usage (Wheel)
0x15, 0x81,        //     Logical Minimum (-127)
0x25, 0x7F,        //     Logical Maximum (127)
0x75, 0x08,        //     Report Size (8)
0x95, 0x04,        //     Report Count (4)
0x81, 0x06,        //     Input (Data,Var,Rel,No Wrap,Linear,Preferred State,No Null Position)
0xC0,              //   End Collection
0x05, 0xFF,        //   Usage Page (Reserved 0xFF)
0x09, 0xC0,        //   Usage (0xC0)
0x75, 0x08,        //   Report Size (8)
0x95, 0x01,        //   Report Count (1)
0x81, 0x02,        //   Input (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position)
0xC0,              // End Collection

// 64 bytes
```

The buttons are currently not recognized, as there is no `HID_USAGE_DESKTOP_POINTER` usage set.

So I would like to add the following to `extract_data` (hid_report.c) to cover this:
```cpp
        {.usage_page   = HID_USAGE_PAGE_BUTTON,
         .global_usage = HID_USAGE_DESKTOP_MOUSE,
         .usage        = 0x0, // none
         .handler      = handle_buttons,
         .receiver     = process_mouse_report,
         .dst          = &iface->mouse.buttons,
         .id           = &iface->mouse.report_id},
```

This way the buttons will start working.

I would be happy to provide a PR for this, but this time I think starting the discussion upfront might make more sense. :wink: 

Greets,
Jan

**Comment by jalmeroth** [comment]
Here's how a typical report looks like when it's parsed:
![swappy-20241208_153141](https://github.com/user-attachments/assets/1e0fce62-542c-4188-80bd-c4e0c4ac3c66)

**Comment by hrvach** [comment]
I think just removing:

```
         .usage        = HID_USAGE_DESKTOP_POINTER,
```

might be a better fix? Having two entries that point to the same handler and one is a wildcard accepting anything seems redundant. This raises a great point that "usage" here should not be mandatory anyway and it would probably improve device compatibility in similar cases. As always - great find :)

**Comment by jalmeroth** [comment]
> This raises a great point that "usage" here should not be mandatory anyway […]

I don't know if you had in mind to remove it for all of them, but I started with the buttons only for now.

**Comment by hrvach** [comment]
> I don't know if you had in mind to remove it for all of them, but I started with the buttons only for now.

Not all of them for now, I'm not sure if the rest are required as I only looked into the buttons one for now. I think it should work OK and improve compatibility across devices for sure, great work! I also need to create an action that auto-builds after a commit ... started doing some refactoring, hopefully the repo will look less crappy soon. :)

**Comment by jalmeroth** [comment]
> I also need to create an action that auto-builds after a commit ...

Take a look here: https://github.com/jalmeroth/deskhopl/blob/main/.github/workflows/build.yml

I would be happy to assist with that!
