### ISSUE TITLE
pico w

### ISSUE THREAD

**Issue by DanPatten** [hrvach/deskhop#24]
I have a pico w instead of a pico, what do I need to do to make that work instead?

**Comment by mparrett** [comment]
I am curious about this too.

**Comment by hrvach** [comment]
Building it with PICO_BOARD=pico_w and removing gpio_put that deals with the LED (as it's wired differently, it will not work as the wifi section controls it) should be sufficient (in theory). I have no way of testing yet; there are plans to try adding a pico_w for bluetooth support...
