### ISSUE TITLE
Alternative digital isolators to ADuM1201BRZ

### ISSUE THREAD

**Issue by takd** [hrvach/deskhop#28]
Would an [ISO7721DR](https://www.ti.com/lit/gpn/iso7721) be a proper substitute for the ADuM1201BRZ? Seems like they are both similar digital isolators in the same packaging, and the former would be more easily obtainable for me.

**Comment by hrvach** [comment]
ISO7721D or ISO7721DR in SOIC-8 seem to be pin-compatible with ADuM1201BRZ and their datasheet suggests even stricter rise times and pulse widths. 

Looks like it would work as a drop-in replacement, and work at least as good. Great find!
