### ISSUE TITLE
Cant enter keys for which a deskhop modifier is needed.

### ISSUE THREAD

**Issue by SyedAmerGilani** [hrvach/deskhop#32]
To enter @ i have to press right alt + q on my keyboard.
But that does not work with deskhop. I suppose because pressing right alt goes in the mouse_zoom_hotkey_handler and further keys are ignored.

**Comment by hrvach** [comment]
Good point. You can recompile without the altgr shortcut, and also please suggest what would be a better choice here - I'm open to ideas (this was a button I never use).

**Comment by SyedAmerGilani** [comment]
I have disabled the key as you suggested, that works for me at the moment.
It is hard to find a single non modifier key that is not used generally. maybe scroll lock?

**Comment by hrvach** [comment]
Many modern keyboards don't have that anymore. I'll try changing it to something else in the future release, or let the altgr through to the OS (also not a bad option).
