### ISSUE TITLE
Feature request: Mouse accelleration

### ISSUE THREAD

**Issue by github-k8n** [hrvach/deskhop#59]
Deskhop is working great, however the fact that there is no accelleration built in is a bit of a bummer. (due to it being an absolute pointing device, i can't set it in the OS itself.

Maybe some simple lookup table or array in the code could be used to determine the mouse movement.
Calculate the (vector) speed and then look up the appropriate multiplication factor..
10 -> 1
20 -> 1.5
30 -> 2

That way everyone could set up their own speed curve.

(Accelleration helps a lot when just flicking the cursor into another screen section but still being able to fine control the movement.)

**Comment by github-k8n** [comment]
Just to clarify, I am NOT talking about switching between computers, that is working great as-is (i set it to 100).
It is about the acceleration of the mouse cursor within the screen.
That's one of the things you just don't notice until it isn't there anymore..

**Comment by hrvach** [comment]
This should not be hard to implement, I just never noticed this as something I miss (but then again I was using a 2$ mouse and thought that was fine too 😀 )

**Comment by Fallingonion** [comment]
I'd like to second this request - I've just built my first deskhop and it's *awesome*, but mouse acceleration would be great!

**Comment by hrvach** [comment]
Implemented. Please check and let me know if you have a better acceleration curve to suggest.

**Comment by github-k8n** [comment]
Thank you! Works like a charm!
(Now i just have to get used again to mouse accelleration after working without it for a while since using deskhop :P )
