### ISSUE TITLE
使用键盘快捷键动态调整鼠标的移动速度

### ISSUE THREAD

**Issue by youxinweizhi** [hrvach/deskhop#75]
鼠标的移动速度在编译固件前由下面的配置定义好的，但是并不能很好的满足需求，是否可以考虑使用键盘快捷键动态调整鼠标的移动速度？
#define MOUSE_SPEED_A_FACTOR_X 30
#define MOUSE_SPEED_A_FACTOR_Y 30

**Comment by hrvach** [comment]
Please be so kind to write in English, my Chinese is not very good :-)
