### ISSUE TITLE
Screenlock on macOS doesn't work

### ISSUE THREAD

**Issue by jalmeroth** [hrvach/deskhop#82]
Hi there,

I noticed that the new feature to lock both devices (`Right ALT + Right Shift + L`) at the same time didn't work for me on macOS.

Deskhop sends `Ctrl + Alt + Q` but it should be `Ctrl + Cmd + Q`: 
<img width="294" alt="Screenshot 2024-04-02 at 20 38 16" src="https://github.com/hrvach/deskhop/assets/4163868/d11e7896-267c-4d4e-b132-8500ce6e383f">

Has this successfully been tested by others? If not I can prepare a PR for this.

Regards,
Jan

**Comment by hrvach** [comment]
Did you configure OS you have connected on each output so the box know which shortcut to send?

**Comment by jalmeroth** [comment]
Yes, I did and I successfully used `KEYBOARD_MODIFIER_LEFTGUI` instead of `KEYBOARD_MODIFIER_LEFTALT`.

**Comment by hrvach** [comment]
Oh, this might be due to the fact my command and option keys are swapped :)
