### ISSUE TITLE
kvm button Caps Lock 

### ISSUE THREAD

**Issue by ASUDCT** [hrvach/deskhop#86]
My system locked capitalization for some unknown reason. When I press the Caps Lock button, deskhop can only perform kvm. I need to unlock capitalization using another keyboard that is not connected to deskhop or a virtual keyboard. This is very inconvenient. Is there any other way to do this？

**Comment by hrvach** [comment]
Yes, if the defaults don't work for you and you prefer to use caps lock, check out user_config.h -  there is an option to redefine it to something else or disable it (search for HOTKEY_TOGGLE). Then just rebuild and you should be good to go.
