### ISSUE TITLE
[WIKI] Add more info on debugging

### ISSUE THREAD

**Issue by jalmeroth** [hrvach/deskhop#90]
Hi there, :wave: 

I collected some info on debugging here: https://github.com/jalmeroth/deskhop/wiki/Debugging and I would like to move it in this wiki.

Some info is coming from here: https://github.com/hrvach/deskhop/issues/21.

Thanks,
Jan

**Comment by hrvach** [comment]
Thank you so much, added to https://github.com/hrvach/deskhop/wiki/Build---Debug-hints and of course credit goes to you. Really appreciate the effort to better document stuff!
