### ISSUE TITLE
8bitdo Retro Keyboard ultimnate tool

### ISSUE THREAD

**Issue by denbrazh** [hrvach/deskhop#93]
Starts with error then crashed 
Error: 未捕获异常： at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type) at System.Single.Parse(String s) at AdvanceSuper.Hid.HIDManage.readGamePadNewVersion(Int32& color, Int32 pid) at AdvanceSuper.SelectPlatform.readversion() at System.Threading.ThreadHelper.ThreadStart_Context(Object state) at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) --- End of stack trace from previous location --- at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) at System.Threading.ThreadHelper.ThreadStart()未捕获异常： at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type) at System.Single.Parse(String s) at AdvanceSuper.Hid.HIDManage.readGamePadNewVersion(Int32& color, Int32 pid) at AdvanceSuper.SelectPlatform.readversion() at System.Threading.ThreadHelper.ThreadStart_Context(Object state) at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) --- End of stack trace from previous location --- at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) at System.Threading.ThreadHelper.ThreadStart()未捕获异常： at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type) at System.Single.Parse(String s) at AdvanceSuper.Hid.HIDManage.readGamePadNewVersion(Int32& color, Int32 pid) at AdvanceSuper.SelectPlatform.readversion() at System.Threading.ThreadHelper.ThreadStart_Context(Object state) at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) --- End of stack trace from previous location --- at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) at System.Threading.ThreadHelper.ThreadStart()

**Comment by hrvach** [comment]
I'm sorry but I don't understand what this report is about - this seems like C# or something...

**Comment by hrvach** [comment]
I'll assume this is due to some keyboard vendor tool for configuration, none of these work by design due to security concerns. Apologies for the inconvenience!
