### ISSUE TITLE
PCB v1.1 - Board A pin 3 additional pad not through-hole

### ISSUE THREAD

**Issue by ddragic** [hrvach/deskhop#96]
First of, awesome project, thanks for making it!

I noticed on PCB rev1 the additional pad for pin 3 (GND) for Board A Pico is not set to Through-hole.
I'm guessing it was just missed and left as SMD pad type?

**Comment by hrvach** [comment]
It's amazing how many times you can look at something and still not see it! 😄 thank you for catching this. I'll try to fix as soon as possible.

**Comment by collinjc** [comment]
I also missed this. Just had boards made. Will this impact functionality?

**Comment by hrvach** [comment]
> I also missed this. Just had boards made. Will this impact functionality?

No, don't worry about it. Will fix soon
